<!-- JavaScript Libraries -->
<script src="{{ URL::asset('kvant42new/assets/vendor/aos/aos.js') }}"></script>
<script src="{{ URL::asset('kvant42new/assets/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ URL::asset('kvant42new/assets/vendor/glightbox/js/glightbox.min.js') }}"></script>
<script src="{{ URL::asset('kvant42new/assets/vendor/isotope-layout/isotope.pkgd.min.js') }}"></script>
<script src="{{ URL::asset('kvant42new/assets/vendor/php-email-form/validate.js') }}"></script>
<script src="{{ URL::asset('kvant42new/assets/vendor/purecounter/purecounter.js') }}"></script>
<script src="{{ URL::asset('kvant42new/assets/vendor/swiper/swiper-bundle.min.js') }}"></script>
<script src="{{ URL::asset('kvant42new/assets/vendor/waypoints/noframework.waypoints.js') }}"></script>
